(function(){
  const nav=document.querySelector('nav');const navButton=document.createElement('button');navButton.dataset.view='workflow';navButton.innerHTML='↝ <span>End-to-end workflow</span>';nav.insertBefore(navButton,nav.firstChild);
  const panel=document.createElement('section');panel.className='panel';panel.id='workflow';document.querySelector('.work').appendChild(panel);
  const stages=[
    {team:'Contact centre',title:'Answer, transcribe, diagnose and start case',view:'contactvoip',record:'CON-88231',action:'VOIP call, caller identity, consent, transcript, vulnerability and Awaab triage captured.'},
    {team:'Housing officer',title:'Welfare, tenancy and access plan',view:'officer',record:'TASK-HO-4418',action:'Household needs checked; welfare visit and safe access arrangement recorded.'},
    {team:'Surveyor',title:'Inspect and approve specification',view:'surveytablet',record:'INS-88142',action:'Room survey, photographs and priced specification approved.'},
    {team:'R&M planning',title:'Allocate resources, materials and PO',view:'rmcontrol',record:'PLAN-204842',action:'DLO and contractor packages scheduled; materials reserved and PO committed.'},
    {team:'Operative / contractor',title:'Attend, build to spec and evidence',view:'mobile',record:'WO-204842',action:'Arrival, progress, photographs, measurements and certificates submitted.'},
    {team:'Quality inspector',title:'Post-inspect, snag or pass',view:'inspections',record:'QA-88142',action:'Completed work checked against original specification; quality outcome recorded.'},
    {team:'Accounts',title:'Three-way match and release payment',view:'commercial',record:'INV-FR-8821',action:'Order, approved variation, evidence and invoice matched; payment released.'}
  ];
  let current=Number(localStorage.getItem('homesafeFlowStep')||0);if(current<0||current>=stages.length)current=0;
  panel.innerHTML=`<div class="flow-hero"><div><span class="kicker">ONE SHARED CASE • CROSS-DEPARTMENT CONTROL</span><h2>Awaab damp report to safe completion and payment</h2><p>Amina Rahman • 14 Orchard Walk • HZ-24019 • one record, seven accountable handoffs</p></div><div><button class="btn alt" id="resetFlow">Reset demonstration</button> <button class="btn" id="nextHandoff">Complete current task & hand off</button></div></div><div class="flow-map" id="flowMap"></div><div class="workflow-grid"><div><div class="card current-task"><span class="kicker">CURRENT OWNER AND ACTION</span><div id="currentTask"></div></div><div class="card" style="margin-top:14px"><span class="kicker">DEPARTMENT INBOXES CREATED BY THE FLOW</span><h2>Live work queues</h2><div id="departmentInboxes"></div></div></div><div><div class="card shared-record"><span class="kicker">SHARED RESIDENT / PROPERTY / CASE RECORD</span><h2>No rekeying between teams</h2><div class="shared-row"><span>Resident & tenancy</span><b>Amina Rahman • secure tenancy • Urdu interpreter</b></div><div class="shared-row"><span>Housing context</span><b>£684.22 arrears • arrangement active • vulnerability flag</b></div><div class="shared-row"><span>Property & compliance</span><b>UPRN 100012345678 • gas/electric current • asbestos known</b></div><div class="shared-row"><span>Safety case</span><b>HZ-24019 • Awaab emergency clock • written summary issued</b></div><div class="shared-row"><span>Repairs & commercial</span><b>WO-204842 • PO-811245 • £1,452.30 committed</b></div><div class="shared-row"><span>Evidence</span><b id="sharedEvidence">Resident report and 4 contact-centre photographs</b></div></div><div class="card" style="margin-top:14px"><span class="kicker">IMMUTABLE HANDOFF TIMELINE</span><h2>Who did what, and why</h2><div class="handoff-timeline" id="handoffTimeline"></div></div></div></div>`;
  const toast=msg=>{const t=document.getElementById('toast');t.textContent='✓ '+msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),3000)};
  function openView(view){const b=document.querySelector('nav button[data-view="'+view+'"]');if(b)b.click()}
  function render(){document.getElementById('flowMap').innerHTML=stages.map((s,i)=>'<button class="flow-step '+(i<current?'done':i===current?'active':'')+'" data-index="'+i+'"><span>'+(i<current?'✓':i+1)+'</span><b>'+s.team+'</b><small>'+s.title+'</small></button>').join('<i>→</i>');const s=stages[current];document.getElementById('currentTask').innerHTML='<div class="task-owner"><div><i class="status-dot amber"></i><b>'+s.team+'</b><small>'+s.record+'</small></div><i class="pill amber">Action required</i></div><h2>'+s.title+'</h2><p>'+s.action+'</p><button class="btn" id="openCurrent">Open '+s.team+' workspace</button>';document.getElementById('openCurrent').onclick=()=>openView(s.view);document.getElementById('departmentInboxes').innerHTML=stages.map((x,i)=>'<button class="inbox-row" data-view="'+x.view+'"><span>'+x.team+'</span><b>'+(i<current?'Completed':i===current?'1 task due':'Waiting for handoff')+'</b><i class="pill '+(i<current?'green':i===current?'amber':'')+'">'+(i<current?'Done':i===current?'Owned':'Queued')+'</i></button>').join('');document.querySelectorAll('.inbox-row').forEach(b=>b.onclick=()=>openView(b.dataset.view));document.getElementById('handoffTimeline').innerHTML=stages.slice(0,current+1).map((x,i)=>'<div class="timeline-event '+(i===current?'now':'')+'"><span></span><div><b>'+x.team+' • '+x.record+'</b><small>'+(i===current?'Task received and ownership accepted':x.action)+'</small></div><time>'+(i===0?'09:12':('0'+(9+i)).slice(-2)+':'+(12+i*6))+'</time></div>').join('');const evidence=['Resident report and 4 contact-centre photographs','Resident impact, vulnerability and access plan added','22 survey photos, readings and signed specification','Resource plan, PO and material reservations linked','Before/during/after photos and certificates linked','Post-inspection outcome and snag evidence linked','Complete golden thread retained with payment record'];document.getElementById('sharedEvidence').textContent=evidence[current];document.getElementById('nextHandoff').textContent=current===stages.length-1?'Complete case & close':'Complete current task & hand off'}
  document.getElementById('nextHandoff').onclick=()=>{if(current===stages.length-1){toast('Case closed with complete resident, safety, repair, quality and financial audit trail');return}const from=stages[current],to=stages[current+1];current++;localStorage.setItem('homesafeFlowStep',current);render();toast(from.team+' completed its task; '+to.team+' now owns the next action')};
  document.getElementById('resetFlow').onclick=()=>{current=0;localStorage.setItem('homesafeFlowStep',0);render();toast('Workflow reset to initial contact-centre report')};
  panel.addEventListener('click',e=>{const step=e.target.closest('.flow-step');if(step)openView(stages[Number(step.dataset.index)].view)});
  navButton.onclick=()=>{document.querySelectorAll('.panel').forEach(x=>x.classList.remove('on'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));panel.classList.add('on');navButton.classList.add('on');document.getElementById('title').textContent='End-to-end workflow';render();scrollTo(0,0)};render();
})();
